k9s:
  cluster: dev
  skin: everforest
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - homepage
      - cert-manager
      - flux-system
      - wallabag
      - default
      - all
      - networking
      - storage
  view:
    active: context
  featureGates:
    nodeShell: false
  proxy: null
