k9s:
  cluster: dev
  skin: transparent
  namespace:
    active: default
    lockFavorites: false
    favorites:
      - flux-system
      - wallabag
      - default
      - all
      - networking
      - storage
  view:
    active: v1/pods
  featureGates:
    nodeShell: false
  proxy: null
