k9s:
  cluster: dev
  skin: transparent
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - flux-system
      - default
      - all
      - networking
      - storage
      - homepage
      - cert-manager
      - wallabag
  view:
    active: pods
  featureGates:
    nodeShell: false
  proxy: null
