k9s:
  cluster: dev
  skin: gruvbox-material-dark-hard
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - external-secrets
      - nextcloud
      - flux-system
      - default
      - all
      - networking
      - storage
      - homepage
      - cert-manager
  view:
    active: pods
  featureGates:
    nodeShell: true
  proxy: null
