k9s:
  cluster: prod
  skin: gruvbox-material-dark-hard
  namespace:
    active: all
    lockFavorites: true
    favorites:
      - blog
      - default
      - all
      - networking
  view:
    active: pods
  featureGates:
    nodeShell: false
  proxy: null
