k9s:
  cluster: prod
  skin: gruvbox-material-dark-soft
  namespace:
    active: default
    lockFavorites: true
    favorites:
      - blog
      - default
      - all
      - networking
  view:
    active: nodes
  featureGates:
    nodeShell: false
  proxy: null
