k9s:
  cluster: prod
  skin: transparent
  namespace:
    active: default
    lockFavorites: true
    favorites:
      - blog
      - default
      - all
      - networking
  view:
    active: context
  featureGates:
    nodeShell: false
  proxy: null
