k9s:
  cluster: prod
  skin: monokai-prod
  namespace:
    active: all
    lockFavorites: true
    favorites:
      - blog
      - default
      - all
      - networking
  view:
    active: ingress
  featureGates:
    nodeShell: false
  proxy: null
