session_name: kali
windows:
  - window_name: notes
    layout: tiled
    panes:
      - cd ~/fr3d && v
  - window_name: kali
    layout: tiled
    panes:
      - cd ~/hackthebox/
  - window_name: host
    layout: tiled
    panes:
      - btop
  - window_name: vpn
    layout: tiled
    panes:
      - htb

