# vim: ft=cfg
# Basic options
default_keybindings = true
use_nerdfont = true
notify = true
gapless = true
flip_status_indicators = true
shuffle = false
repeat = 'off'

[keybindings]
## unbinded: nN, c, eE, xX
######################################
# Song controls
######################################

##################
# Fast forward / rewind
##################
"b" = "seek -1000"
"f" = "seek +1000"
"Shift+b" = "seek -10000"
"Shift+f" = "seek +10000"

##################
# Play / pause
##################
"p" = "playpause"
"Enter" = "play"
"s" = "stop"

##################
# Track manipulation
##################
"Shift+h" = "previous"
"Shift+l" = "next"
"r" = "repeat"
"z" = "shuffle"
"Shift+d" = "delete"
"Shift+s" = "save"
# Open context menu
"Shift+o" = "open current"
"o" = "open selected"
"Shift+a" = "goto artist"
"a" = "goto album"

##################
# Queue
##################
# Add to queue
"Space" = "queue"
"Ctrl+s" = "save queue"
# Move selected song up/down in the queue
"Shift+j" = "shift down 1"
"Shift+k" = "shift up 1"
"Shift+c" = "clear"
# Open the context menu for a Spotify link in the clipboard
"Ctrl+v" = "insert"

######################################
# Sound
######################################
"=" = "volup 1"
"-" = "voldown 1"
"[" = "volup 5"
"]" = "voldown 5"


######################################
# Movements
######################################
"F1" = "focus queue"
"F2" = "focus library"
"F3" = "focus search"
"1" = "focus queue"
"2" = "focus library"
"Ctrl+q" = "focus queue"
# Navigation
"Down" = "move down 1"
"Shift+g" = "move bottom"
"g" = "move top"
"Left" = "move left 1"
"Right" = "move right 1"
"Ctrl+d" = "move down 5"
"Ctrl+u" = "move up 5"
"Up" = "move up 1"
"h" = "move left 1"
"j" = "move down 1"
"k" = "move up 1"
"Ctrl+e" = "move down 1"
"Ctrl+y" = "move up 1"
"l" = "move right 1"
"." = "move playing"
"q" = "back"

######################################
# Sorting
######################################
"t" = "sort added d"
"Shift+t" = "sort title a"

######################################
# Sharing
######################################
"Shift+y" = "share selected"
"y" = "share current"

######################################
# Other
######################################
"Shift+q" = "quit"
"Shift+z" = "quit"
"?" = "help"
"Shift+u" = "update"


[theme]
background = "#000000"
primary = "#abb2bf"
secondary = "#434852"
title = "#61afef"
playing = "#89ca78"
playing_bg = "#2c313a"
playing_selected = "#abb2bf"
highlight = "#c8ccd4"
highlight_bg = "#434852"
error = "#abb2bf"
error_bg = "#ef596f"
statusbar_progress = "#2bbac5"
statusbar_bg = "#000000"
statusbar = "#e5c07b"
cmdline = "#abb2bf"
cmdline_bg = "#000000"
search_match = "#e5c07b"
