# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.selection]
background = "#484844"
text = "#b5b3aa"

[colors.normal]
black = "#000000"
cyan = "#c6c5fe"
white = "#b5b3aa"
blue = "#96cbfe"
magenta = "#ff73fd"
yellow = "#ffffb6"
red = "#ff6c60"
green = "#a8ff60"

[colors.primary]
foreground = "#b5b3aa"
background = "#000000"

[colors.bright]
black = "#6c6c66"
cyan = "#c6c5fe"
white = "#fdfbee"
blue = "#96cbfe"
magenta = "#ff73fd"
yellow = "#ffffb6"
red = "#ff6c60"
green = "#a8ff60"

[colors.cursor]
text = "#000000"
cursor = "#b5b3aa"
