# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.selection]
text = "#d7dae0"
background = "#302d41"

[colors.cursor]
cursor = "#d7dae0"
text = "#1e1e28"

[colors.normal]
black = "#1e1e28"
cyan = "#b5e8e0"
blue = "#96cdfb"
red = "#f28fad"
magenta = "#ddb6f2"
yellow = "#fae3b0"
green = "#abe9b3"
white = "#d7dae0"

[colors.bright]
black = "#575268"
cyan = "#b5e8e0"
blue = "#96cdfb"
red = "#f28fad"
magenta = "#ddb6f2"
yellow = "#fae3b0"
green = "#abe9b3"
white = "#c9cbff"

[colors.primary]
background = "#1e1e28"
foreground = "#d7dae0"
