[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[colors.cursor]
cursor = "#FFFFFF"
text   = "#000000"

[colors.selection]
background = "#FFFFFF"
text       = "#000000"

[colors.normal]
black   = "#000000"
red     = "#FF2400"
green   = "#808080"
yellow  = "#FBEC5D"
blue    = "#C0C0C0"
magenta = "#787878"
cyan    = "#C3D1EB"
white   = "#C0C0C0"

[colors.bright]
black   = "#808080"
red     = "#FF2400"
green   = "#808080"
yellow  = "#FBEC5D"
blue    = "#0000FF"
magenta = "#787878"
cyan    = "#C3D1EB"
white   = "#FFFFFF"
