# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.normal]
yellow = "#f5d098"
cyan = "#b3e3ca"
magenta = "#f3c0e5"
red = "#f57f82"
blue = "#b2caed"
white = "#96b4aa"
green = "#cbe3b3"
black = "#374145"

[colors.primary]
foreground = "#f8f9e8"
background = "#232a2e"

[colors.bright]
yellow = "#f5d098"
cyan = "#b3e3ca"
magenta = "#f3c0e5"
red = "#f57f82"
blue = "#b2caed"
white = "#adc9bc"
green = "#cbe3b3"
black = "#6f8788"

[colors.selection]
text = "#f8f9e8"
background = "#374145"

[colors.cursor]
cursor = "#cbe3b3"
text = "#171c1f"
