# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.selection]
background = "#3c3836"
text = "#d4be98"

[colors.bright]
cyan = "#89b482"
magenta = "#d3869b"
white = "#d4be98"
blue = "#7daea3"
green = "#a9b665"
red = "#ea6962"
black = "#504945"
yellow = "#d8a657"

[colors.primary]
background = "#1d2021"
foreground = "#d4be98"

[colors.cursor]
cursor = "#d4be98"
text = "#1d2021"

[colors.normal]
cyan = "#89b482"
magenta = "#d3869b"
white = "#d4be98"
blue = "#7daea3"
green = "#a9b665"
red = "#ea6962"
black = "#504945"
yellow = "#d8a657"
