# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.normal]
magenta = "#d3869b"
black = "#202020"
yellow = "#d8a657"
white = "#ddc7a1"
cyan = "#89b482"
green = "#a9b665"
blue = "#7daea3"
red = "#ea6962"

[colors.primary]
background = "#202020"
foreground = "#ddc7a1"

[colors.selection]
text = "#202020"
background = "#504945"

[colors.bright]
magenta = "#d3869b"
black = "#5a524c"
yellow = "#d8a657"
white = "#fbf1c7"
cyan = "#89b482"
green = "#a9b665"
blue = "#7daea3"
red = "#ea6962"

[colors.cursor]
text = "#202020"
cursor = "#ddc7a1"
