# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.primary]
foreground = "#ebdbb2"
background = "#282828"

[colors.selection]
text = "#ebdbb2"
background = "#504945"

[colors.cursor]
text = "#282828"
cursor = "#ebdbb2"

[colors.bright]
black = "#665c54"
yellow = "#d79921"
green = "#98971a"
magenta = "#b16286"
white = "#f9f5d7"
blue = "#458588"
cyan = "#689d6a"
red = "#cc241d"

[colors.normal]
black = "#282828"
yellow = "#d79921"
green = "#98971a"
magenta = "#b16286"
white = "#ebdbb2"
blue = "#458588"
cyan = "#689d6a"
red = "#cc241d"
