# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.normal]
magenta = "#00ff00"
white = "#00ff00"
cyan = "#00ff00"
blue = "#00ff00"
red = "#00ff00"
black = "#0d0d0d"
green = "#00ff00"
yellow = "#00ff00"

[colors.selection]
text = "#ffffff"
background = "#1a1a1a"

[colors.primary]
background = "#0d0d0d"
foreground = "#00ff00"

[colors.bright]
magenta = "#00ff00"
white = "#00ff00"
cyan = "#00ff00"
blue = "#00ff00"
red = "#00ff00"
black = "#ffffff"
green = "#00ff00"
yellow = "#00ff00"

[colors.cursor]
text = "#0d0d0d"
cursor = "#00ff00"
