# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.primary]
foreground = "#ffffff"
background = "#1a2332"

[colors.bright]
cyan = "#5cecc6"
blue = "#5cb2ff"
magenta = "#c16cfa"
white = "#5c6370"
green = "#c5f467"
yellow = "#ffaf00"
red = "#ff3e3e"
black = "#3e4452"

[colors.selection]
background = "#3e4452"
text = "#ffffff"

[colors.cursor]
cursor = "#5cb2ff"
text = "#1a2332"

[colors.normal]
cyan = "#5cecc6"
blue = "#5cb2ff"
magenta = "#c16cfa"
white = "#ffffff"
green = "#c5f467"
yellow = "#ffcc5c"
red = "#ff8484"
black = "#1a2332"
