# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.cursor]
cursor = "#c8d3f5"
text = "#222436"

[colors.bright]
cyan = "#b2ebff"
magenta = "#caabff"
yellow = "#ffd8ab"
white = "#c8d3f5"
black = "#444a73"
green = "#c7fb6d"
blue = "#9ab8ff"
red = "#ff8d94"

[colors.primary]
foreground = "#cccccc"
background = "#101010"

[colors.selection]
text = "#000000"
background = "#cccccc"

[colors.normal]
cyan = "#86e1fc"
magenta = "#c099ff"
yellow = "#ffc777"
white = "#828bb8"
black = "#1b1d2b"
green = "#c3e88d"
blue = "#82aaff"
red = "#ff757f"
