# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.selection]
background = "#2a2a2d"
text = "#c9c7cd"

[colors.primary]
background = "#161617"
foreground = "#c9c7cd"

[colors.cursor]
cursor = "#c9c7cd"
text = "#27272a"

[colors.bright]
magenta = "#ecaad6"
red = "#ffae9f"
black = "#353539"
green = "#9dc6ac"
blue = "#b9aeda"
yellow = "#f0c5a9"
white = "#cac9dd"
cyan = "#f591b2"

[colors.normal]
magenta = "#e29eca"
red = "#f5a191"
black = "#27272a"
green = "#90b99f"
blue = "#aca1cf"
yellow = "#e6b99d"
white = "#c1c0d4"
cyan = "#ea83a5"
