# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.normal]
white = "#f1f1f1"
blue = "#a1a1a1"
magenta = "#66b2b2"
cyan = "#d1d1d1"
black = "#303030"
yellow = "#bababa"
red = "#deeeed"
green = "#1bfd9c"

[colors.selection]
background = "#313131"
text = "#1c1c1c"

[colors.bright]
white = "#ffffff"
blue = "#b1b1b1"
magenta = "#49c4c4"
cyan = "#d7d7d7"
black = "#4d4d4d"
yellow = "#e1e1e1"
red = "#708090"
green = "#a6ffc9"

[colors.cursor]
cursor = "#c0c0c0"
text = "#1c1c1c"

[colors.primary]
background = "#1c1c1c"
foreground = "#c0c0c0"
