# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.primary]
background = "#2b2b2b"
foreground = "#ffffff"

[colors.cursor]
text = "#2b2b2b"
cursor = "#62d8f1"

[colors.bright]
magenta = "#ff005f"
white = "#ffffff"
red = "#fc1a70"
green = "#a4e400"
blue = "#62d8f1"
black = "#444444"
yellow = "#ffff87"
cyan = "#0087ff"

[colors.selection]
text = "#ffffff"
background = "#444444"

[colors.normal]
magenta = "#ff005f"
white = "#e6e6e6"
red = "#fc1a70"
green = "#a4e400"
blue = "#62d8f1"
black = "#000001"
yellow = "#ffff87"
cyan = "#0087ff"
