# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.normal]
cyan = "#86e1fc"
green = "#c3e88d"
blue = "#82aaff"
black = "#1b1d2b"
white = "#828bb8"
yellow = "#ffc777"
magenta = "#c099ff"
red = "#ff757f"

[colors.selection]
background = "#1b1f26"
text = "#191d24"

[colors.cursor]
text = "#191d24"
cursor = "#c0c8d8"

[colors.bright]
cyan = "#b2ebff"
green = "#c7fb6d"
blue = "#9ab8ff"
black = "#444a73"
white = "#c8d3f5"
yellow = "#ffd8ab"
magenta = "#caabff"
red = "#ff8d94"

[colors.primary]
background = "#242933"
foreground = "#c0c8d8"
