# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.primary]
background = "#242933"
foreground = "#c0c8d8"

[colors.selection]
background = "#1b1f26"
text = "#828bb8"

[colors.cursor]
text = "#191d24"
cursor = "#c0c8d8"

[colors.normal]
black = "#1b1d2b"
cyan = "#86e1fc"
blue = "#82aaff"
white = "#828bb8"
magenta = "#c099ff"
yellow = "#ffc777"
green = "#c3e88d"
red = "#ff757f"

[colors.bright]
black = "#444a73"
cyan = "#b2ebff"
blue = "#9ab8ff"
white = "#c8d3f5"
magenta = "#caabff"
yellow = "#ffd8ab"
green = "#c7fb6d"
red = "#ff8d94"
