# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.primary]
foreground = "#eceff4"
background = "#2e3440"

[colors.bright]
black = "#444a73"
yellow = "#ffd8ab"
blue = "#9ab8ff"
green = "#c7fb6d"
white = "#c8d3f5"
magenta = "#caabff"
red = "#ff8d94"
cyan = "#b2ebff"

[colors.normal]
black = "#1b1d2b"
yellow = "#ffc777"
blue = "#82aaff"
green = "#c3e88d"
white = "#828bb8"
magenta = "#c099ff"
red = "#ff757f"
cyan = "#86e1fc"

[colors.selection]
background = "#384356"
text = "#c8d3f5"

[colors.cursor]
cursor = "#88c0d0"
text = "#2e3440"
