# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.primary]
foreground = "#adadcc"
background = "#111111"

[colors.selection]
text = "#a8a6f5"
background = "#262830"

[colors.normal]
magenta = "#6c6b9b"
green = "#647977"
black = "#666a82"
yellow = "#c4959c"
red = "#ba5f60"
cyan = "#436285"
white = "#6f6f83"
blue = "#6172a0"

[colors.cursor]
text = "#121315"
cursor = "#adadcc"

[colors.bright]
magenta = "#a8a6f5"
green = "#9bbdb8"
black = "#666a82"
yellow = "#d2af98"
red = "#ad82a2"
cyan = "#6397cf"
white = "#adadcc"
blue = "#95b1fc"
