# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.primary]
background = "#32302f"
foreground = "#ddc7a1"

[colors.selection]
text = "#fbf1c7"
background = "#5a524c"

[colors.normal]
black = "#32302f"
white = "#ddc7a1"
cyan = "#89b482"
blue = "#7daea3"
magenta = "#d3869b"
red = "#ea6962"
yellow = "#d8a657"
green = "#a9b665"

[colors.cursor]
cursor = "#ddc7a1"
text = "#32302f"

[colors.bright]
black = "#7c6f64"
white = "#fbf1c7"
cyan = "#89b482"
blue = "#7daea3"
magenta = "#d3869b"
red = "#ea6962"
yellow = "#d8a657"
green = "#a9b665"
