# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.primary]
background = "#000000"
foreground = "#cccccc"

[colors.selection]
background = "#1d414d"
text = "#f8f8f8"

[colors.cursor]
text = "#000000"
cursor = "#cccccc"

[colors.bright]
black = "#767676"
cyan = "#7c9cae"
white = "#f8f8f8"
blue = "#8eccdd"
magenta = "#b98eb2"
yellow = "#b99353"
red = "#d88568"
green = "#83a471"

[colors.normal]
black = "#000000"
cyan = "#7c9cae"
white = "#cccccc"
blue = "#8eccdd"
magenta = "#b98eb2"
yellow = "#b99353"
red = "#d88568"
green = "#83a471"
