# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.cursor]
cursor = "#dcdccc"
text = "#383838"

[colors.bright]
black = "#6f6f6f"
white = "#ffffff"
cyan = "#93e0e3"
blue = "#7cb8bb"
magenta = "#dc8cc3"
red = "#dca3a3"
yellow = "#e0cf9f"
green = "#5f7f5f"

[colors.primary]
foreground = "#dcdccc"
background = "#383838"

[colors.selection]
text = "#dca3a3"
background = "#606060"

[colors.normal]
black = "#383838"
white = "#dcdccc"
cyan = "#93e0e3"
blue = "#7cb8bb"
magenta = "#dc8cc3"
red = "#dca3a3"
yellow = "#e0cf9f"
green = "#5f7f5f"
