# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.cursor]
text = "#000000"
cursor = "#c1c1c1"

[colors.bright]
red = "#5f8787"
black = "#333333"
magenta = "#999999"
yellow = "#79241f"
white = "#c1c1c1"
blue = "#888888"
cyan = "#aaaaaa"
green = "#f8f7f2"

[colors.normal]
red = "#5f8787"
black = "#000000"
magenta = "#999999"
yellow = "#79241f"
white = "#c1c1c1"
blue = "#888888"
cyan = "#aaaaaa"
green = "#f8f7f2"

[colors.selection]
background = "#222222"
text = "#c1c1c1"

[colors.primary]
foreground = "#c1c1c1"
background = "#000000"
