# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.bright]
white = "#c1c1c1"
cyan = "#aaaaaa"
magenta = "#999999"
blue = "#888888"
black = "#333333"
green = "#f8f7f2"
red = "#5f8787"
yellow = "#79241f"

[colors.normal]
white = "#c1c1c1"
cyan = "#aaaaaa"
magenta = "#999999"
blue = "#888888"
black = "#000000"
green = "#f8f7f2"
red = "#5f8787"
yellow = "#79241f"

[colors.selection]
background = "#222222"
text = "#c1c1c1"

[colors.cursor]
cursor = "#c1c1c1"
text = "#000000"

[colors.primary]
foreground = "#c1c1c1"
background = "#000000"
