k9s:
  cluster: memphis
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - cert-manager
      - storage
      - all
      - monitoring
      - default
      - renovate
      - flux-system
      - database
      - external-secrets
  view:
    active: v1/pods all
  featureGates:
    nodeShell: false
  proxy: null
