k9s:
  cluster: memphis
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - all
      - storage
      - cert-manager
      - renovate
      - freshrss
      - default
      - flux-system
      - monitoring
      - database
  view:
    active: v1/nodes
  featureGates:
    nodeShell: false
  proxy: null
